### ISSUE TITLE
issue for Mac 10.13

### ISSUE THREAD

**Issue by mario78** [miyako/4d-plugin-usb#3]
[usbTest.zip](https://github.com/miyako/4d-plugin-usb/files/4299054/usbTest.zip)

plugin istnt executable under
Mac 10.13.6
4D 17R6

**Comment by miyako** [comment]
I guess the fix is to use homebrew on **Majave** to create a compatible static libusb, then rebuild the plugin on **Catalina**.

**Comment by miyako** [comment]
I am sorry but I only have Catalina. 

If you have a macOS 10.13, you might be in the best position to compile from source.

There is also a related project

https://github.com/miyako/4d-plugin-hidapi
